@ECHO OFF
PROMPT PF$G
::cls

MD "C:\Program Files (x86)\Telex Communications\C-Soft"
copy AMBE+2_pwplugin.dll "C:\Program Files (x86)\Telex Communications\C-Soft"
copy CSoftDesigner.exe "C:\Program Files (x86)\Telex Communications\C-Soft"
copy csoftruntime.exe "C:\Program Files (x86)\Telex Communications\C-Soft"
copy csoftruntime_libFNP.dll "C:\Program Files (x86)\Telex Communications\C-Soft"
copy libeay32.dll "C:\Program Files (x86)\Telex Communications\C-Soft"
copy telexIcon.ico "C:\Program Files (x86)\Telex Communications\C-Soft"
copy TelexLicenseServer-x86-1.2.0.0.exe "C:\Program Files (x86)\Telex Communications\C-Soft"
copy unins000.dat "C:\Program Files (x86)\Telex Communications\C-Soft"
copy unins000.exe "C:\Program Files (x86)\Telex Communications\C-Soft"

MD "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers"
copy adhb-4.cat "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers"
copy ADHB-4.inf "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers"
copy dpinst.exe "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers"
copy dpinst.xml "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers"
copy telexIcon.ico "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers"

MD "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers\amd64"
copy WdfCoInstaller01007.dll "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers\amd64"
copy WinUSBCoInstaller.dll "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers\amd64"

MD "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers\i386"
copy WdfCoInstaller01007.dll "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers\i386"
copy WinUSBCoInstaller.dll "C:\Program Files (x86)\Telex Communications\C-Soft\usb_drivers\i386"

MD "C:\Program Files (x86)\Telex Communications\License Server"
copy Bosch.Operational.dll "C:\Program Files (x86)\Telex Communications\License Server"
copy Bosch.Security.UserManagementService.ActivationLib.dll "C:\Program Files (x86)\Telex Communications\License Server"
copy BBosch.Security.UserManagementService.ActivationLib_libFNP.dll "C:\Program Files (x86)\Telex Communications\License Server"
copy Bosch.UserInterfaces.Mvvm.dll "C:\Program Files (x86)\Telex Communications\License Server"
copy BOSCHST.exe "C:\Program Files (x86)\Telex Communications\License Server"
copy BOSCHST.opt "C:\Program Files (x86)\Telex Communications\License Server"
copy BOSCHST_libFNP.dll "C:\Program Files (x86)\Telex Communications\License Server"
copy BOSCHST_LicMgr.lic "C:\Program Files (x86)\Telex Communications\License Server"
copy FNP_Act_Installer.dll "C:\Program Files (x86)\Telex Communications\License Server"
copy installanchorservice.exe "C:\Program Files (x86)\Telex Communications\License Server"
copy installs.exe "C:\Program Files (x86)\Telex Communications\License Server"
copy lmgrd.exe "C:\Program Files (x86)\Telex Communications\License Server"
copy lmreread.exe "C:\Program Files (x86)\Telex Communications\License Server"
copy uninstallanchorservice.exe "C:\Program Files (x86)\Telex Communications\License Server"

MD "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Telex Communications"
copy "C-Soft Designer.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Telex Communications"
copy "C-Soft Runtime.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Telex Communications"

copy "C-Soft Designer.lnk" "C:\Users\Public\Desktop"
copy "C-Soft Runtime.lnk" "C:\Users\Public\Desktop"
copy "C-Soft Sample Files.lnk" "C:\Users\Public\Desktop"

MD "C:\ProgramData\Telex Communications\audio_folder"

MD "C:\ProgramData\Telex Communications\design_folder"
copy Readme.txt "C:\ProgramData\Telex Communications\design_folder"
copy DeleteDefaultVeg.cmd "C:\ProgramData\Telex Communications\design_folder"

MD "C:\ProgramData\Telex Communications\design_folder\icons"

MD "C:\ProgramData\Telex Communications\License Activation Tool"

MD "C:\ProgramData\Telex Communications\logs_folder"

MD "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy ADHB4_Default.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy ADHB4_Default.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy "AIS Sample.veg" "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy API_Demo-SystemList.xml "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy API_Demo.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy Default_SIP.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy DFSI_Danels_Test-SystemList.xml "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy DFSI_Daniels_Test.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy DFSI_Server_Example-SystemList.xml "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy DFSI_Server_Example.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy Example3.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy FleetSyncSystemList.xml "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy FleetSync_Default.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy MDC-1200_Default.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy MDC_Demo.xml "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy Mototrbo_Default.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy Mototrbo_Default.xml "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy "NEXEDGE IP Interface Demo.veg" "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy "NEXEDGE IP Interface Demo.xml" "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy outerspacevenus.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy P25_Radio.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy Penguin.veg "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy "Radio Dispatch Solutions.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy "Telex Test Lab.veg" "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"
copy VOIProven50.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Designs"

MD "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy 511.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy 588Mall_Final3 750_480vss.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy 759_Airport_2_1 1000_800.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy 911.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy abort.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy adm_1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy alarm_bell.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "alerts red.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy alerts.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Alerts1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy AMBERX.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy AMBERXs.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy areacode.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy arrow1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Aurora.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE2-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE2-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE3-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE3-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE4-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE4-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE4-XL.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE5-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE5-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE6-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BADGE6-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BeepHigh.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BeepMute.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy BeepMute1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy blkgry.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy bolt.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy CallHistory.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "Camera-icon sm.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy cdm_1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy cdm_2.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "College Campus.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Contacts.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy CSOFT-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy CSOFT-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy daniels.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy DHS-1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy DHS-med.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy DHS-sml.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy DHS-xl.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy DHS.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy door.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "elite_126 new.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy elite_126.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy elite_127.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy elite_128.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy elite_1_127.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy elite_520.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "Emer Clear Red.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "Emer Clear.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "Emer Tones Red.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "Emer Tones.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Emergency.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Emergency1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT-XL.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT2-LX.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT2-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT2-X.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT3-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT3-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT3-XL.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT4-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EMT4-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy EPA.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy exchange.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy FAA.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy FBI.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy FIRE-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy FIRE-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy FIRE-XL.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy green-check2.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "group page.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy hazmat.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Headset-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Headset-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy HH-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy HH-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy HH-XL.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy icled.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "input dwn.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "input up.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "intercom tx.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "intercom tx2.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy intercom.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy IP223-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy IP223-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "LA CTNY.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "Master PTT up.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "Master PTT.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "mic down.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy mic.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "monitor down.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy monitor.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "multi sel tx red.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "multi sel TX.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Muppet-Beaker[1].bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy NEO10_L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy NEO10_S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy NEXTEL.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "nexusIP Logo.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy nws.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy NXDN.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy page.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Pages.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy PASP.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch 1 TX red.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch 1 TX.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch 2 TX red.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch 2 TX.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch 2.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch 2a.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch 3 TX red.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch 3 TX.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "Patch 3.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch TX reda.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch TX.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "patch TXa.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Patch.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy patch1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy PFDD.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy PFDU.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "PH hold.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "PH offhk.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "PH onhk-1.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "PH onhk.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy PHONED.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy PHONEU.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Play.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "power plant C.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "power1-L - Copy.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy power1-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "power1-S - Copy.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy power1-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "power1-XL - Copy.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy power1-XL.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "power2-L - Copy.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy power2-L.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy power2-S.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy power2-XL.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy PPD.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy ptt.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy ptt1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy red_x_mark2.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy rxled.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy rxled1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "scan off.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "scan on.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "send page.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy SPRINT.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "sup dwn.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "sup up.BMP" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy TB9100.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy TB9100b.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy telex.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy TLXVOIP2.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "tool bar cop.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "tool bar cop1.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Tools.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy Transparent.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy txled.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy unmute.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy uscg.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy VOIProven50-1.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy VOIProven50.bmp "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"
copy "white pages.bmp" "C:\Users\Public\Documents\Telex Communications\C-Soft\Images"

MD "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "1 Tornado Alert.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "10 Shelter All Clear.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "11 Shelter Test.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "12 Shelter Test Complete.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "2 Tornado All Clear.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "3 Tornado Test.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "4 Tornado Test Complete.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "5 Lightning.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "6 Lightning All Clear.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "7 Lightning Test.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "8 Lightning Test Complete.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "9 Shelter.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy Alert.wav "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "all units.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "fire Z1 F1.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "fire Z1 F3.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "fire Z3 F1.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "intu Loading Z2.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy "intu main gnd fl.wav" "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy tone.wav "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy tone2.wav "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"
copy tone3.wav "C:\Users\Public\Documents\Telex Communications\C-Soft\Sounds"

GOTO:EOF

PROMPT